name: CD Pipeline

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VM and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}

          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-app:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d -p 3000:3000 --name myapp ${{ secrets.DOCKER_USERNAME }}/devops-app:latest
